name: palazzo

services:
  palazzo:
    build:
      context: .
    env_file: .env
    environment:
      - ICECAST_PORT=${ICECAST_PORT:-8000}
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD:-palazzo-source}
    ports:
      - "127.0.0.1:${ICECAST_PORT:-8000}:${ICECAST_PORT:-8000}"
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./tsconfig.json
        - action: rebuild
          path: ./tsconfig.build.json
    restart: unless-stopped
