FROM ubuntu:jammy

RUN apt-get update && apt-get install -y --no-install-recommends \
  liquidsoap \
  lame \
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /stream

WORKDIR /stream

ENTRYPOINT ["liquidsoap", "/stream/stream.liq"]
