FROM node:22

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
  liquidsoap \
  lame \
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install && npm cache clean --force

COPY nest-cli.json tsconfig.json ./

EXPOSE 3100

CMD ["npm", "run", "start:dev"]
